version: '3.9'

services:
  database:
    image: postgres
    container_name: database
    ports:
      - '5433:5432'
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - students-network
  backend:
    image: secured-students
    ports:
      - '8080:8080'
    environment:
      STUDENTS_DB_USER: ${DATABASE_USER}
      STUDENTS_DB_PASSWORD: ${DATABASE_PASSWORD}
      STUDENTS_DB_NAME: ${DATABASE_NAME}
      STUDENTS_DB_HOST: database:5432
    depends_on:
      - database
    networks:
      - students-network

networks:
  students-network:
    driver: bridge
