name: Docker Image CI example

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Демка
      run: echo Workflow прошёл успешно, ура!
